### ISSUE TITLE
Meteor + node-notify: __dirname not defined

### ISSUE THREAD

**Issue by afang** [mikaelbr/node-notifier#102]
I can't seem to figure out why this module can't be used with Meteor.

`import notifier from 'node-notify';`

the full error log:

```
/Users/workspace/.meteor/packages/meteor-tool/.1.1.13-modules.8.1w9uct0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
						throw(ex);
						      ^
ReferenceError: __dirname is not defined
    at meteorInstall.node_modules.node-notifier.notifiers.notificationcenter.js (node_modules/node-notifier/notifiers/notificationcenter.js:5:1)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:202:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
    at meteorInstall.node_modules.node-notifier.index.js (node_modules/node-notifier/index.js:6:1)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:202:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
    at meteorInstall.server.shopify.js (server/shopify.js:3:18)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:202:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
    at /Users/workspace/Desktop/shopify-desktop/.meteor/local/build/programs/server/app/app.js:207:1
    at /Users/workspace/Desktop/shopify-desktop/.meteor/local/build/programs/server/boot.js:242:10
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/workspace/.meteor/packages/meteor-tool/.1.1.13-modules.8.1w9uct0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /Users/workspace/Desktop/shopify-desktop/.meteor/local/build/programs/server/boot.js:137:5
Exited with code: 8
Your application is crashing. Waiting for file change.
```

**Comment by mikaelbr** [comment]
`node-notifier` uses a "node.js global" variable named `__dirname` to resolve file lookup relative to the script file location. I don't know how meteor handles that, but it seems as you can use `npm.require('node-notifier')`, ref: https://github.com/meteor/meteor/issues/6022
