### ISSUE TITLE
Uncaught Error : spawn EACCES

### ISSUE THREAD

**Issue by Monstreur** [mikaelbr/node-notifier#173]
Hi,
First, i'm working on a project for my school. We need to send OS notification so thanks for this module.
My issue is that we encountred an "Uncaught Error : spawn EACCES" on mac from this module.
Do you know what cause this ?
I search and i try to run "sudo npm start" if it was an issue about security access but nothing happened.

**Comment by kurisubrooks** [comment]
EACCES would usually only be thrown when you can't access a system port, so i'm going to go ahead and assume you're using an older version of macOS that does not support native notifications, so node-notifier tries to fall back to Growl (which uses a web server to interact).

Might I ask what version of macOS you are running?

**Comment by Monstreur** [comment]
Failed on MacOS 10.12.5 (the latest, i think).

**Comment by devildant** [comment]
hello, i have same problem with OSX 10.11
{ Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:399:9)
    at Object.exports.execFile (child_process.js:160:15)
    at Object.module.(anonymous function) [as execFile] (ELECTRON_ASAR.js:219:18)
    at Object.module.exports.fileCommandJson (/Users/devildant/Desktop/HomeStation.app/Contents/Resources/app.asar/node_modules/node-notifier/lib/utils.js:79:13)
    at NotificationCenter.notify (XXX/Contents/Resources/app.asar/node_modules/node-notifier/notifiers/notificationcenter.js:87:20)
    at Object.addNotification (XXX/Contents/Resources/app.asar/appConfiguration/systemTray.js:106:22)
    at Object.trayNotify (XXX/Contents/Resources/app.asar/appConfiguration/entity.js:66:20)
    at BrowserWindow.<anonymous> (XXX/Contents/Resources/app.asar/main.js:520:35) code: 'EACCES', errno: 'EACCES', syscall: 'spawn' }
Error: spawn EACCES

**Comment by kurisubrooks** [comment]
@devildant Node Notifier cannot be run from within Electron. Please check [this section](https://github.com/mikaelbr/node-notifier#within-electron-packaging) of the README for more information.

**Comment by kurisubrooks** [comment]
@Monstreur Out of curiosity, are you also running Node Notifier under Electron?

**Comment by devildant** [comment]
hello, yes i use electron :)

**Comment by kurisubrooks** [comment]
Please refer to this section of the README to see how you can successfully run Node Notifier alongside Electron.

https://github.com/mikaelbr/node-notifier#within-electron-packaging

**Comment by devildant** [comment]
thanks it's perfect
i use electron packager and it's necessary to remove option --asar=true and add 
--asar.unpackDir=\"node_modules/node-notifier/vendor/**\"
