### ISSUE TITLE
npm run example:mac fails with '.../coulson.jpg' is not a valid URI

### ISSUE THREAD

**Issue by landon9720** [mikaelbr/node-notifier#185]
I pulled this repo and tried `npm run example:mac`.

```
~/s/node-notifier> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73
~/s/node-notifier> node --version
v7.9.0
~/s/node-notifier> npm run example:mac

> node-notifier@5.1.2 example:mac /Users/landon/src/node-notifier
> node ./example/advanced.js

{ '0':
   { Error: Command failed: /Users/landon/src/node-notifier/vendor/terminal-notifier -title "Phil Coulson" -subtitle "Agent of S.H.I.E.L.D." -message "If I come out, will you shoot me? 'Cause then I won't come out." -sound "Funk" -appIcon "/Users/landon/src/node-notifier/example/coulson.jpg" -contentImage "/Users/landon/src/node-notifier/example/coulson.jpg" -open "file:///Users/landon/src/node-notifier/example/coulson.jpg" -timeout "5" -json "true"
   2017-07-17 10:26:27.129 terminal-notifier[95091:30675084] 'file:///Users/landon/src/node-notifier/example/coulson.jpg' is not a valid URI.

       at ChildProcess.exithandler (child_process.js:205:12)
       at emitTwo (events.js:106:13)
       at ChildProcess.emit (events.js:194:7)
       at maybeClose (internal/child_process.js:899:16)
       at Socket.<anonymous> (internal/child_process.js:342:11)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:191:7)
       at Pipe._handle.close [as _onclose] (net.js:510:12)
     killed: false,
     code: 1,
     signal: null,
     cmd: '/Users/landon/src/node-notifier/vendor/terminal-notifier -title "Phil Coulson" -subtitle "Agent of S.H.I.E.L.D." -message "If I come out, will you shoot me? \'Cause then I won\'t come out." -sound "Funk" -appIcon "/Users/landon/src/node-notifier/example/coulson.jpg" -contentImage "/Users/landon/src/node-notifier/example/coulson.jpg" -open "file:///Users/landon/src/node-notifier/example/coulson.jpg" -timeout "5" -json "true"' },
  '1': '',
  '2': {} }
```
Thank you.

L

**Comment by mikaelbr** [comment]
This is due to https://github.com/julienXX/terminal-notifier/issues/215. New version of terminal notifier not released yet, but patch exist.

**Comment by mikaelbr** [comment]
Should be fixed now.
