### ISSUE TITLE
EACCES issue with npm@5.4

### ISSUE THREAD

**Issue by sandro-pasquali** [mikaelbr/node-notifier#199]
OSX 10.12.4
Node v8.4.0

`npm 5.4` introduces permission errors when using `node-notifier`. Cannot use `node-notifier` if installed with `npm 5.4`. Probably something to do with new npm, but filing just in case this is relevant to `node-notifier` itself.

To replicate

```
> npm i -g npm@5.3
> npm i node-notifier

// index.js
const notifier = require('node-notifier');
notifier.notify('Message');
notifier.notify({
    'title': 'My notification',
    'message': 'Hello, there!'
});

> node index.js

(system notification appears. Works).

> npm i -g npm@5.4
> npm i node-notifier

>node index.js

Error: spawn EACCES
    at _errnoException (util.js:1041:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at Object.exports.execFile (child_process.js:208:15)
    at Object.module.exports.fileCommandJson (Desktop/temp/eaccess_npm5.4/node_modules/node-notifier/lib/utils.js:79:13)
    at NotificationCenter.notify (Desktop/temp/eaccess_npm5.4/node_modules/node-notifier/notifiers/notificationcenter.js:87:20)
    at Object.<anonymous> (Desktop/temp/eaccess_npm5.4/index.js:3:10)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)

> npm i -g npm@5.3
> node index.js

Error: spawn EACCES
    at _errnoException (util.js:1041:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at Object.exports.execFile (child_process.js:208:15)
    at Object.module.exports.fileCommandJson (Desktop/temp/eaccess_npm5.4/node_modules/node-notifier/lib/utils.js:79:13)
    at NotificationCenter.notify (Desktop/temp/eaccess_npm5.4/node_modules/node-notifier/notifiers/notificationcenter.js:87:20)
    at Object.<anonymous> (Desktop/temp/eaccess_npm5.4/index.js:3:10)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)

> npm i node-notifier
> node index.js

(works)

```

**Comment by jeremywiebe** [comment]
I traced this down to incorrect file permissions on the vendored `terminal-notifier.app`.

```sh
$ ls -l node_modules/webpack-notifier/node_modules/node-notifier/vendor/terminal-notifier.app/Contents/MacOS
total 144
-rw-r--r--  1 ******  *****    72K 25 May  2016 terminal-notifier
$ chmod +x node_modules/webpack-notifier/node_modules/node-notifier/vendor/terminal-notifier.app/Contents/MacOS/terminal-notifier
$ ls -l node_modules/webpack-notifier/node_modules/node-notifier/vendor/terminal-notifier.app/Contents/MacOS
total 144
-rwxr-xr-x  1 ******  *****    72K 25 May  2016 terminal-notifier*
```

**Comment by mikaelbr** [comment]
Does this also happen on the master branch?

**Comment by jeremywiebe** [comment]
@mikaelbr Yes. 

```sh
$ ls
total 16
-rw-r--r--  1 jeremy  staff   168B  6 Sep 13:58 index.js
-rw-r--r--  1 jeremy  staff    89B  6 Sep 13:59 package.json
$ npm --version
5.4.0
$ cat package.json
{
    "dependencies": {
        "node-notifier": "mikaelbr/node-notifier#master"
    }
}
$ npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN test No description
npm WARN test No repository field.
npm WARN test No license field.

added 6 packages in 1.552s
$ cat index.js
// index.js
const notifier = require('node-notifier');
notifier.notify('Message');
notifier.notify({
    'title': 'My notification',
    'message': 'Hello, there!'
});
$ node index.js
internal/child_process.js:325
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at _errnoException (util.js:1041:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at Object.exports.execFile (child_process.js:208:15)
    at Object.module.exports.fileCommandJson (/Users/jeremy/Development/test/node_modules/node-notifier/lib/utils.js:79:13)
    at NotificationCenter.notify (/Users/jeremy/Development/test/node_modules/node-notifier/notifiers/notificationcenter.js:78:11)
    at Object.<anonymous> (/Users/jeremy/Development/test/index.js:3:10)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
$ _
```

**Comment by jeremywiebe** [comment]
Follow-up.  If I clone the repo, the `terminal-notifier` file has the execute bit set. It's only if I `npm install` with a git reference, or install via the npm repo that it's missing the execute bit.

**Comment by mikaelbr** [comment]
Looks related to https://github.com/npm/npm/issues/17899 and maybe https://github.com/npm/npm/issues/18383?

**Comment by jeremywiebe** [comment]
@mikaelbr Good eye!  Looks like npm v5.4.1 fixes it too: https://github.com/npm/npm/releases/tag/v5.4.1

**Comment by mikaelbr** [comment]
Ah, great! Happy to see it worked out. Thanks for all the research!

**Comment by jwhitmarsh** [comment]
Just a heads up to anyone who get's here - nvm v5.4.1 does fix it, but you have to reinstall your node_modules.
