### ISSUE TITLE
NotifySend throws when no `notify-send` binary is found

### ISSUE THREAD

**Issue by jankeromnes** [mikaelbr/node-notifier#265]
I don't have a `notify-send` binary on my platform, which caused the following, somewhat confusing bug in the `notable` app: https://github.com/fabiospampinato/notable/issues/253

The root error (that was getting lost between many Promises and try/catches/re-throws) was this:

```
{ Error: not found: notify-send
    at getNotFoundError (/workspace/notable/node_modules/which/which.js:13:12)
    at Function.whichSync [as sync] (/workspace/notable/node_modules/which/which.js:134:9)
    at NotifySend.notify (/workspace/notable/node_modules/node-notifier/notifiers/notifysend.js:65:27)
    at P (/workspace/notable/node_modules/pify/index.js:32:6)
    at new Promise (<anonymous>)
    at /workspace/notable/node_modules/pify/index.js:6:9
    at ret (/workspace/notable/node_modules/pify/index.js:56:76)
    at Object.send (/workspace/notable/node_modules/pacco/src/utilities/notification.js:34:60)
    at task (/workspace/notable/node_modules/pacco/src/tasks/build/notification.js:21:25)
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)
    at asyncRunner (/workspace/notable/node_modules/async-done/index.js:55:18)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9) code: 'ENOENT' }
```

Maybe NotifySend could catch this exception, and fall back to some other notification mechanism? (It's a bit unfortunate that a missing binary can break an otherwise successful Gulp build.) Thanks! 😄

**Comment by mikaelbr** [comment]
Hey, thanks for reporting this. To me this can look like an "user issue". node-notifier propagates the error (see here https://github.com/mikaelbr/node-notifier/blob/master/notifiers/notifysend.js#L69)

And something using this module converts it to a promise and doesnt catch the error of that promise. I don't think node-notifier should swollow errors as the consumer should be able to choose what they want to do if it does't work.
