### ISSUE TITLE
node-notifier not working with yarn berry (PnP)

### ISSUE THREAD

**Issue by HeadFox** [mikaelbr/node-notifier#301]
Hi :)
I am using node-notifier with jest notify. 
I am no issue by using yarn with node_modules but I have a problem using yarn PnP.

Dep:
- jest: 24.9.0
- node-notifier: 5.4.3

I have an error I have no idea how to debug it. If anyone has any ideas on how to debug this, it will be really appreciated :)

Here is the error : 
```
Error: spawn ENOTDIR
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at spawn (child_process.js:540:9)
    at Object.execFile (child_process.js:224:17)
    at Object.module.exports.fileCommandJson (/Users/user/xxx/xxx/frontend/.yarn/cache/node-notifier-npm-5.4.3-068ef79075-1.zip/node_modules/node-notifier/lib/utils.js:83:13)
    at NotificationCenter.notify (/Users/user/xxx/xxx/frontend/.yarn/cache/node-notifier-npm-5.4.3-068ef79075-1.zip/node_modules/node-notifier/notifiers/notificationcenter.js:81:11)
    at NotifyReporter.onRunComplete (/Users/user/xxx/xxx/frontend/.yarn/cache/@jest-reporters-npm-24.9.0-a0b7efbd72-1.zip/node_modules/@jest/reporters/build/notify_reporter.js:172:31)
    at /Users/user/xxx/xxx/frontend/.yarn/cache/@jest-core-npm-24.9.0-67a39bf91e-1.zip/node_modules/@jest/core/build/ReporterDispatcher.js:200:29
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/user/xxx/xxx/frontend/.yarn/cache/@jest-core-npm-24.9.0-67a39bf91e-1.zip/node_modules/@jest/core/build/ReporterDispatcher.js:10:24)
    at _next (/Users/user/xxx/xxx/frontend/.yarn/cache/@jest-core-npm-24.9.0-67a39bf91e-1.zip/node_modules/@jest/core/build/ReporterDispatcher.js:30:9)
```

**Comment by merceyz** [comment]
This has been fixed upstream in Yarn, we automatically unplug packages with native files
